---
title: Homework 5 - Coding a navigation system
author: Krish Patel
date: 3/25/2024
format:
  html:
    embed-resources: true
    theme: cosmo
    resource-path: [./assets]
---

* [LINK to GITHUB](https://github.com/cmsc-vcu/cmsc475-sp2024-hw5-kriishpatell)
* [LINK to FIGMA PROTOTYPE CODE](https://www.figma.com/proto/3wOBKq1UzBVtcePt55Cksj?node-id=0-1&t=xOlgfhpcAl13OtMH-6)

# Introduction

The user should be able to navigate throughout all the panels and be able to visualize more about who I am and what defines me best. The story told in these panels is more to describe the different meanings behind some of the themes and how they describe me using animations and where those interpretations come from.

# Navigation Goals

I want the users to be able to learn more about me and have a fun experience navigating through the panels and interacting with the different cards. Some of the main messages that I want to convey are love and adventure that are indicated throughout the calling cards.

# Navigation Elements

Users will move through the different calling cards using mostly arrows. There is a section in the theme panels where you can select a specific panel using the specifier buttons on the bottom. Check mark buttons and reset buttons are provided for the user to indicate when they are done viewing or if they want to restart the journey.

# Figma mockup

<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width=800 height=450 src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2F3wOBKq1UzBVtcePt55Cksj%2FHW4%3Fembed_host%3Dshare%26kind%3Dproto%26node-id%3D16-142%26page-id%3D0%253A1%26scaling%3Dmin-zoom%26starting-point-node-id%3D16%253A142%26t%3D9KfoV8AAUBi5c1H6-1%26type%3Ddesign%26mode%3Ddesign" data-external = "1" allowfullscreen></iframe>

The user should be able to navigate through the panels using the arrows that are provided and return to previous panels if they would like to take another look.

# User Testing

I asked what they felt when they went through the panels and if there was anything that could make their experience more seamless. They responded that there were too many buttons, so I might make a change for that. I’m thinking maybe I implement some of the animated objects in my panels into the actual navigation. They also said that they liked the animations and that if they knew beforehand that the themed panels were about me, they would better understand the reasoning for them.

# Implementation

```{=html}
<center>
<iframe
src="https://editor.p5js.org/kriishpatell/full/KBNiPmSxn"
style="border: 1px solid rgba(0, 0, 0, 0.1);"
width="800"
height="450"  
data-external="1"
allowfullscreen="allowfullscreen"
webkitallowfullscreen="webkitallowfullscreen"
mozallowfullscreen="mozallowfullscreen"
allow="geolocation *; microphone *; camera *; midi *; encrypted-media *; autoplay *; clipboard-write *; display-capture *"
></iframe>
</center>
```

# Reflection

I think I spent around 7-8 hours on this project. Configuring all the classes so that they could work seamlessly took up the majority of my time, as I was encountering a lot of issues with the pathing of certain functions. I think if I just practiced with classes a little more before starting on the project, it wouldn't have taken as much time and I would have created a better product. It was satisfying to see that everything was functional, however the difficulties that I had with making the prototype look a little bit appealing was difficult and I had to resort to some quick sketches to create my buttons, image, etc. I don't think that I can really say anything about time, because I was given a lot more time than I think that I needed but I really procrastinated, but given more time I think that I would make it so that the buttons appear and disappear on certain panels like I had planned in my Figma prototype. 
