---
title: Homework 6 - Bringing it all together
author: default author
date: last-modified
format:
  html:
    embed-resources: true
    theme: cosmo
---

* [LINK to GITHUB](https://github.com/cmsc-vcu/cmsc475-sp2024-hw6-template)

(this is the sample document.  You need to make it your own.)

(Your report should follow the outline below, found under the easter eggs.)

# Introduction

- Explain the your dynamic calling card
- Who is your audience?  What are your messages?

# Figma mockup

- Include a link to your Figma mockup from homework 4 in an iframe.
- Explain how to use it in this section.

```{=html}
<center>
<iframe
src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FQJss2lSSmmUMKkKodCWxN2%2FHomework-4---Prototype%3Ftype%3Ddesign%26t%3DnIV2fhIRzGgxc44k-1%26scaling%3Dscale-down%26page-id%3D0%253A1%26node-id%3D3-2%26starting-point-node-id%3D3%253A2%26mode%3Ddesign"
style="border: 1px solid rgba(0, 0, 0, 0.1);"
width="800" height="450"  
data-external="1"
allowfullscreen
></iframe>
</center>
```

# Implementation

In this section you show off your implementation of your dynamic calling card.

Point the iframe below to your combined navigation and panels p5js application.

BE SURE to change the ./sketches/. to ./full/. so your script shows full screen and not in the editor.

```{=html}
<center>
<iframe
src="https://editor.p5js.org/jleonard99/full/w1mu4OeEB"
style="border: 1px solid rgba(0, 0, 0, 0.1);"
width="800"
height="450"  
data-external="1"
allowfullscreen="allowfullscreen"
webkitallowfullscreen="webkitallowfullscreen"
mozallowfullscreen="mozallowfullscreen"
allow="geolocation *; microphone *; camera *; midi *; encrypted-media *; autoplay *; clipboard-write *; display-capture *"
></iframe>
</center>
```

# Reflection

* This is the most important section of the assignment!
* Stop, Pause, Breath, and Consider.

1. How much time did you spend on the assignment?
1. What activities consumed the most of your time? 
1. How could you have been better prepared to tackle this assignment (in terms of skills or knowledge)?
1. What did you find most satisfying about this assignment?
1. What did you find most difficult about this assignment? 
1. Given more time, what would you do differently?

